name: Notify Discord on Push

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit info to Discord
        run: |
          # Build the JSON payload using a heredoc.
          # IMPORTANT: The "EOF" marker below must have no indentation.
          json=$(cat <<EOF
{
  "embeds": [{
    "title": "New Commit in Repository",
    "description": "A new commit has been pushed to the **main** branch.",
    "color": 3447003,
    "fields": [
      {
        "name": "Commit SHA",
        "value": "${{ github.sha }}",
        "inline": true
      },
      {
        "name": "Commit Message",
        "value": "${{ github.event.head_commit.message }}",
        "inline": false
      },
      {
        "name": "Committer",
        "value": "${{ github.actor }}",
        "inline": true
      },
      {
        "name": "Commit URL",
        "value": "[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
        "inline": false
      },
      {
        "name": "Repository",
        "value": "${{ github.repository }}",
        "inline": true
      },
      {
        "name": "Branch",
        "value": "${{ github.ref }}",
        "inline": true
      },
      {
        "name": "Files Changed",
        "value": "${{ github.event.head_commit.modified }}",
        "inline": false
      }
    ],
    "footer": {
      "text": "GitHub Actions | ${{ github.actor }}",
      "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}"
    },
    "timestamp": "${{ github.event.head_commit.timestamp }}",
    "author": {
      "name": "${{ github.actor }}",
      "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}"
    },
    "thumbnail": {
      "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
    }
  }]
}
EOF
          )
          echo "$json"  # (Optional) Print the JSON payload for debugging.
          curl -X POST -H "Content-Type: application/json" -d "$json" "${{ secrets.DISCORD_WEBHOOK_URL }}"
