name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit info to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          --data "$(echo '{
            "embeds": [{
              "title": "New Commit in Repository",
              "description": "A new commit has been pushed to the **main** branch.",
              "color": 3447003,
              "fields": [
                {
                  "name": "Commit SHA",
                  "value": "'"$GITHUB_SHA"'",
                  "inline": true
                },
                {
                  "name": "Commit Message",
                  "value": "'"${{ github.event.head_commit.message }}"'",
                  "inline": false
                },
                {
                  "name": "Committer",
                  "value": "'"$GITHUB_ACTOR"'",
                  "inline": true
                },
                {
                  "name": "Commit URL",
                  "value": "[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                  "inline": false
                },
                {
                  "name": "Repository",
                  "value": "${{ github.repository }}",
                  "inline": true
                },
                {
                  "name": "Branch",
                  "value": "${{ github.ref }}",
                  "inline": true
                },
                {
                  "name": "Files Changed",
                  "value": "'"${{ github.event.head_commit.modified }}"'",
                  "inline": false
                }
              ],
              "footer": {
                "text": "GitHub Actions | '${{ github.actor }}'",
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'",
              "author": {
                "name": "'"$GITHUB_ACTOR"'",
                "icon_url": "https://avatars.githubusercontent.com/$GITHUB_ACTOR"
              },
              "thumbnail": {
                "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "image": {
                "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "author": {
                "name": "'"$GITHUB_ACTOR"'",
                "icon_url": "https://avatars.githubusercontent.com/$GITHUB_ACTOR"
              }
            }]
          }')" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
