name: GitHub-Profile-3D-Contrib

on:
  schedule: # Runs every 8 hours
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git pull origin main --rebase
          
          git add -A .
          git commit -m "generated"
          git push origin main
